version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-yarn
workflows:
  example-workflow:
    jobs:
      - example-job