version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    executor:
      name: node/default
      tag: '12.22.3'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run tests

workflows:
  test_my_app:
    jobs:
      - test