name: Deploy preview

on:
  pull_request:
    branches:
      - develop

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    #environment: preview
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
        env:
          REACT_APP_INFURA_API_KEY: ${{ secrets.REACT_APP_INFURA_API_KEY }}
          REACT_APP_PORTIS_ID: ${{ secrets.REACT_APP_PORTIS_ID }}
          REACT_APP_FORTMATIC_API_KEY: ${{ secrets.REACT_APP_FORTMATIC_API_KEY }}
          REACT_APP_BALANCER_POOL_URL: ${{ secrets.REACT_APP_BALANCER_POOL_URL }}
          REACT_APP_BALANCER_SUBGRAPH_URL: ${{ secrets.REACT_APP_BALANCER_SUBGRAPH_URL }}
          REACT_APP_BALANCER_POOLS_ADDRESSES: ${{ secrets.REACT_APP_BALANCER_POOLS_ADDRESSES }}
          REACT_APP_UNI_POOLS_ADDRESSES: ${{ secrets.REACT_APP_UNI_POOLS_ADDRESSES }}
          REACT_APP_SUSHI_POOLS_ADDRESSES: ${{ secrets.REACT_APP_SUSHI_POOLS_ADDRESSES }}
          REACT_APP_HALO_TOKEN_ADDRESS_KOVAN: ${{ secrets.REACT_APP_HALO_TOKEN_ADDRESS_KOVAN }}
          REACT_APP_HALO_REWARDS_ADDRESS_KOVAN: ${{ secrets.REACT_APP_HALO_REWARDS_ADDRESS_KOVAN }}
          REACT_APP_HALOHALO_ADDRESS_KOVAN: ${{ secrets.REACT_APP_HALOHALO_ADDRESS_KOVAN }}
          REACT_APP_HALO_TOKEN_ADDRESS_RINKEBY: ${{ secrets.REACT_APP_HALO_TOKEN_ADDRESS_RINKEBY }}
          REACT_APP_HALO_REWARDS_ADDRESS_RINKEBY: ${{ secrets.REACT_APP_HALO_REWARDS_ADDRESS_RINKEBY }}
          REACT_APP_HALOHALO_ADDRESS_RINKEBY: ${{ secrets.REACT_APP_HALOHALO_ADDRESS_RINKEBY }}
          REACT_APP_HALO_TOKEN_ADDRESS_GOERLI: ${{ secrets.REACT_APP_HALO_TOKEN_ADDRESS_GOERLI }}
          REACT_APP_HALO_REWARDS_ADDRESS_GOERLI: ${{ secrets.REACT_APP_HALO_REWARDS_ADDRESS_GOERLI }}
          REACT_APP_HALOHALO_ADDRESS_GOERLI: ${{ secrets.REACT_APP_HALOHALO_ADDRESS_GOERLI }}
          REACT_APP_HALO_TOKEN_ADDRESS_BSC_TESTNET: ${{ secrets.REACT_APP_HALO_TOKEN_ADDRESS_BSC_TESTNET }}
          REACT_APP_HALO_REWARDS_ADDRESS_BSC_TESTNET: ${{ secrets.REACT_APP_HALO_REWARDS_ADDRESS_BSC_TESTNET }}
          REACT_APP_HALOHALO_ADDRESS_BSC_TESTNET: ${{ secrets.REACT_APP_HALOHALO_ADDRESS_BSC_TESTNET }}
          REACT_APP_HALO_TOKEN_ADDRESS_MATIC_MUMBAI: ${{ secrets.REACT_APP_HALO_TOKEN_ADDRESS_MATIC_MUMBAI }}
          REACT_APP_HALO_REWARDS_ADDRESS_MATIC_MUMBAI: ${{ secrets.REACT_APP_HALO_REWARDS_ADDRESS_MATIC_MUMBAI }}
          REACT_APP_HALOHALO_ADDRESS_MATIC_MUMBAI: ${{ secrets.REACT_APP_HALOHALO_ADDRESS_MATIC_MUMBAI }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HALO_DEV_EB31C }}'
          projectId: halo-dev-eb31c
          target: dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
